name: sales
channels:
  - conda-forge
dependencies:
  - python==3.9.13
  - pandas==1.4.4
  - scikit-learn==1.1.2
  - jupyter==1.0.0
  - matplotlib==3.5.3
  - seaborn==0.12.0
  - pycodestyle==2.9.1
  - pytest==7.1.3
  - pytest-cov==3.0.0
  - pytest-pycodestyle==2.2.0
  # Pip
  - pip==22.2.2