version: 2

sources:
  - name: sales
    description: "Raw data"
    database: sales
    tables:
      - name: sales
        description: "Fact sales"
      - name: budget
        description: "Fact budget"