version: 2

sources:
  - name: sales
    description: "Raw data"
    tables:
      - name: sales
        description: "Fact sales"
      - name: budget
        description: "Fact budget"

models:
  - name: base_products
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: category
        tests:
          - not_null
      - name: segment
        tests:
          - not_null
  - name: base_geography
    columns:
      - name: zipcode
        tests:
          - unique
          - not_null
  - name: base_date
    columns:
      - name: date
        tests:
          - unique
          - not_null
  - name: base_customers
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: zipcode
        test:
          - not_null
  - name: base_manufacturers
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: name
        test:
          - unique
          - not_null
  - name: base_transactions
    columns:
      - name: productid
        test:
          - not_null
      - name: date
        test:
          - not_null
      - name: customerid
        test:
          - not_null
      - name: units
        test:
          - not_null
      - name: unit_price
        test:
          - not_null
      - name: unit_cost
        test:
          - not_null
      - name: manufacturerid
        test:
          - not_null